# Generated by Django 4.2.11 on 2024-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_table', models.CharField(max_length=128)),
                ('entity_pk', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('DELETED', 'Deleted'), ('UPDATED', 'Updated')], max_length=16)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='news_comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='news_post',
        ),
    ]
